//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {

        private static Entities _jjj;

        public Entities()
            : base("name=Entities")
        {
        }

        public static Entities GetContext() 
        {
            if (_jjj == null) _jjj = new Entities();
            return _jjj;
        }
        
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Group_p> Group_p { get; set; }
        public virtual DbSet<Instruktor> Instruktor { get; set; }
        public virtual DbSet<People> People { get; set; }
        public virtual DbSet<Pol> Pol { get; set; }
        public virtual DbSet<Kod_podrazdel> Kod_podrazdel { get; set; }
    }
}
