//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class People
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public Nullable<System.DateTime> date_bir { get; set; }
        public int id_pol { get; set; }
        public Nullable<int> id_group { get; set; }
    
        public virtual Group_p Group_p { get; set; }
        public virtual Pol Pol { get; set; }
    }
}
